<a href="https://colab.research.google.com/github/diegogh1002/Estadistica/blob/main/limpieza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('csv.csv')
df.head()

,Marca temporal,Dirección de correo electrónico,¿En qué semestre te encuentras actualmente?,¿Qué carrera estudias?,¿Eres alumno regular?,Procedencia (dónde naciste),¿Tienes hermanos?,¿Cuál es la marca de tu teléfono?,Modelo del teléfono,Capacidad del teléfono,Plan o prepago del teléfono,Tiempo que llevas con tu teléfono,Tu teléfono es,Género,¿Trabajas?,Edad,¿Qué teléfono te gustaría tener?
0,3/9/2026 17:30:44,fespinozagarcia0105@gmail.com,Tercero,Ciencia de Datos,NaN,Estado de México,NaN,Honor,Honor x7a,128 GB,Plan,Entre 2 y 3 años,Nuevo,Mujer,Sí,21,NaN
1,3/9/2026 18:02:01,gisellemerino2702@gmail.com,Tercero,Ciencia de Datos,NaN,Estado de México,NaN,Apple,15 pro max,256 GB,Prepago,Entre 6 meses y 1 año,Nuevo,Mujer,No,21,NaN
2,3/9/2026 18:19:25,mildredcaravantes@gmail.com,Primero,Ciencia de Datos,NaN,Estado de México,NaN,Apple,iphone 16 pro max,256 GB,Plan,Entre 1 y 2 años,Nuevo,Mujer,No,20,NaN
3,3/9/2026 18:37:08,garcia.hernandez.edgar.alessandro@gmail.com,Tercero,Ciencia de Datos,NaN,CDMX,NaN,Apple,iPhone 16 Pro Max,256 GB,Plan,Entre 1 y 2 años,Nuevo,Hombre,No,19,NaN
4,3/9/2026 20:56:29,diegobus022@gmail.com,Tercero,Ciencia de Datos,NaN,Otro,NaN,Apple,iPhone 13 Pro max,512 GB,Prepago,Entre 1 y 2 años,Segunda mano,Hombre,No,19,NaN

In [4]:
display(df.describe(include='all'))

,Marca temporal,Dirección de correo electrónico,¿En qué semestre te encuentras actualmente?,¿Qué carrera estudias?,¿Eres alumno regular?,Procedencia (dónde naciste),¿Tienes hermanos?,¿Cuál es la marca de tu teléfono?,Modelo del teléfono,Capacidad del teléfono,Plan o prepago del teléfono,Tiempo que llevas con tu teléfono,Tu teléfono es,Género,¿Trabajas?,Edad,¿Qué teléfono te gustaría tener?
count,511,511,511,511,482,511,482,511,511,511,511,511,511,511,511,511,481
unique,500,511,8,4,2,18,2,13,388,7,2,5,2,2,2,8,15
top,3/18/2026 13:01:30,ruligamarons@gmail.com,Cuarto,Ingeniería en Sistemas,Sí,CDMX,Sí,Apple,iPhone 14,256 GB,Plan,Entre 1 y 2 años,Nuevo,Hombre,No,19,Samsung
freq,2,1,113,267,290,275,410,152,9,195,305,163,436,374,341,131,180